// 印刷ビューに埋め込む CSS とスクリプト（旧版とバイト単位で同じにすること。書き換え禁止）

export const PRINT_STYLE = `@page{size:A4 landscape;margin:8mm}*{box-sizing:border-box;-webkit-print-color-adjust:exact;print-color-adjust:exact}:root{color-scheme:light}body{margin:0;background:#e2e8f0;font-family:-apple-system,"Hiragino Sans","Yu Gothic",Meiryo,sans-serif;color:#172554;font-size:10px}
.toolbar{position:sticky;top:0;z-index:5;display:flex;flex-wrap:wrap;gap:8px 14px;align-items:center;background:#fff;padding:10px 16px;border-bottom:1px solid #cbd5e1;font-size:13px}.toolbar .days{display:flex;gap:6px;flex-wrap:wrap}.toolbar button{font:inherit;font-size:13px;font-weight:700;border-radius:7px;padding:7px 12px;cursor:pointer;border:1px solid #cbd5e1;background:#fff;color:#475569}.toolbar button.on{background:#172554;border-color:#172554;color:#fff}.toolbar button.primary{background:#2563eb;border-color:#2563eb;color:#fff}.toolbar label{display:flex;gap:5px;align-items:center;font-weight:600;color:#475569;cursor:pointer}.toolbar .note{color:#64748b;font-size:12px;width:100%}
.sheet{background:#fff;width:297mm;max-width:calc(100% - 24px);min-height:210mm;margin:16px auto;padding:8mm;box-shadow:0 2px 10px #0f172a26}.hide,body.no-people .sheet.people,body:not(.all) .people-all{display:none}
.dh{display:flex;justify-content:space-between;align-items:flex-end;gap:12px;border-bottom:2px solid #172554;padding-bottom:4px;margin-bottom:5px}.dh h2{font-size:17px;margin:0}.eyebrow{margin:0;font-size:9px;font-weight:800;letter-spacing:1px;color:#2563eb}.meta{margin:0;color:#475569;text-align:right;font-size:10.5px}.meta small{color:#94a3b8;font-size:9px}.warn{color:#c2410c}.legend{margin:0 0 5px;color:#64748b;font-size:9px}.legend .t{margin:0 2px 0 6px}.legend .p{display:inline-block}
table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #cbd5e1;padding:4px 4px;vertical-align:top}col.tc{width:15mm}thead th{font-size:11px;line-height:1.25;text-align:center;padding:4px 2px}th.store{font-size:12.5px;padding:4px}th.role{font-weight:700}th.time{text-align:center;background:#f8fafc;font-size:12px;white-space:nowrap}th.time small{display:block;font-size:8px;color:#94a3b8;font-weight:500}.first{border-left:2px solid #475569}tr{break-inside:avoid}td{position:relative}td.off{background:repeating-linear-gradient(135deg,#fff 0 5px,#f1f5f9 5px 10px)}td.open{background:#fff7ed}
.p{display:inline-flex;align-items:center;gap:1px;margin:1px 4px 1px 0;font-size:12.5px;font-weight:650;white-space:nowrap;line-height:1.35}.p.gap{color:#c2410c;border:1px dashed #fb923c;border-radius:3px;padding:0 3px;font-weight:500;font-size:9.5px}.t{display:inline-block;font-size:9px;font-weight:800;border-radius:2px;padding:0 2px;line-height:1.4}.t.hot{background:#ffe4e6;color:#be123c}.t.ice{background:#e0f2fe;color:#0369a1}.short{position:absolute;top:1px;right:2px;font-style:normal;font-size:8px;font-weight:800;color:#c2410c}td.open>.short+.p{margin-top:0}td:has(.short){padding-right:18px}
.f{display:none}body.full .f{display:inline}body.full .s{display:none}
.store-main{background:#dbeafe;color:#1d4ed8}.store-second{background:#ffedd5;color:#c2410c}.store-kurea{background:#ede9fe;color:#6d28d9}.store-prep{background:#fef3c7;color:#92400e}th.role.store-main{background:#eff6ff}th.role.store-second{background:#fff7ed}th.role.store-kurea{background:#f5f3ff}th.role.store-prep{background:#fffbeb}
.people-all table{table-layout:auto}.people-all td{text-align:left;font-size:9.5px}.people-all td div{white-space:nowrap}.people-all tbody th{text-align:left;white-space:nowrap;background:#f8fafc}.people-all .hours{font-weight:700;color:#1d4ed8}.people-all .total{text-align:right;font-weight:700;color:#1d4ed8}.people-all td.off{background:none;color:#94a3b8}
table.grid{border:2px solid #000;font-family:"Hiragino Sans","Yu Gothic",Meiryo,sans-serif}.grid th,.grid td{border:1px solid #000;padding:0 3px;height:var(--rowh,10mm);font-size:11.5px;line-height:1.2;vertical-align:middle;white-space:nowrap;overflow:hidden;color:#000;text-align:left;font-weight:500}.grid thead th{background:#fff;font-weight:700;text-align:center;font-size:10px;height:6mm;padding:1px 2px}.grid thead th small{display:block;font-size:8px;font-weight:600;color:#334155}.grid col.tc{width:14mm}.grid th.time{background:#fff;text-align:center;font-weight:700;font-size:10.5px}.grid thead th.time{background:#fff}.grid thead th.store-main{background:#dbeafe;color:#1e3a8a}.grid thead th.store-second{background:#ffedd5;color:#9a3412}.grid thead th.store-kurea{background:#ede9fe;color:#5b21b6}.grid thead th.store-prep{background:#fef3c7;color:#92400e}.grid thead th.store-clean{background:#fce7f3;color:#9d174d}.grid thead th.role.store-main{background:#eff6ff}.grid thead th.role.store-second{background:#fff7ed}.grid thead th.role.store-kurea{background:#f5f3ff}.grid thead th.role.store-prep{background:#fffbeb}.grid thead th.role.store-clean{background:#fdf2f8}.grid tbody tr.band>*{background:#f1f5f9}.grid thead tr:last-child th{border-bottom:2px solid #000}.grid tbody tr.hour>*{border-top:1.5px solid #000}.grid tbody td.na{background:#000!important}.grid tbody td.open{background:#fff}.grid .first{border-left:2px solid #000}.grid thead th.num{height:auto;font-weight:600}.grid.dense col.tc{width:13mm}.grid th.time small{display:inline;font-size:9px;font-weight:500;color:#64748b}.grid th.time .car{display:block;font-size:7.5px;font-weight:600;color:#64748b;line-height:1.1}.grid th.time .car.zero{color:#dc2626;font-weight:800}.grid.dense th.time{font-size:10px;padding:0 2px}.grid.dense td{font-size:10px;padding:0 2px}.grid td small{float:right;font-size:8px;color:#475569;margin-left:2px}body.full .grid td{white-space:normal;font-size:9.5px}.grid .s,.grid .f{display:inline}.grid .f{display:none}body.full .grid .f{display:inline}body.full .grid .s{display:none}
.drip-mark{margin-left:2px;font-size:9.5px;font-weight:800}.grid td .drip-mark{position:absolute;top:1px;right:1px;margin:0;font-size:7.5px;line-height:1}.drip-mark.all{color:#94a3b8}.drip-mark .hot{color:#dc2626}.drip-mark .ice{color:#2563eb}.legend .drip-mark{margin:0 1px 0 4px}.store-clean{background:#fce7f3;color:#be185d}
.toolbar .modes{display:flex;gap:0}.toolbar .modes button{border-radius:0}.toolbar .modes button:first-child{border-radius:7px 0 0 7px}.toolbar .modes button:last-child{border-radius:0 7px 7px 0;margin-left:-1px}.toolbar select{font:inherit;font-size:13px;padding:5px 8px;border:1px solid #cbd5e1;border-radius:6px}
body[data-mode=tt] .shift-only,body[data-mode=tt] .day,body[data-mode=tt] .people-all{display:none!important}body:not([data-mode=tt]) .tt-only,body:not([data-mode=tt]) .ttday{display:none!important}
.pm{table-layout:fixed;width:100%;border:2px solid #000;font-family:"Hiragino Sans","Yu Gothic",Meiryo,sans-serif}.pm th,.pm td{border:1px solid #000;padding:1px 2px;font-size:9px;line-height:1.15;text-align:center;vertical-align:middle;height:var(--rowh,7mm);color:#000;overflow:hidden}.pm thead th{background:#fff;font-size:9.5px;font-weight:700;height:auto;padding:3px 1px;border-bottom:2px solid #000}.pm thead small{display:block;font-weight:500;font-size:7.5px}.pm .pm-corner,.pm tbody th{width:12mm;font-size:9px;background:#fff;font-weight:700}.pm tbody th small{font-weight:500;color:#555}.pm tr.hour>*{border-top:1.5px solid #000}.pm td.on{font-weight:700}.pm td.store-main{background:#dbeafe;color:#1e3a8a}.pm td.store-second{background:#ffedd5;color:#9a3412}.pm td.store-kurea{background:#ede9fe;color:#5b21b6}.pm td.store-prep{background:#fef3c7;color:#92400e}.pm td.store-clean{background:#fce7f3;color:#9d174d}.pm td.brk{color:#555}.pm td.conflict{font-weight:800;background:#fee2e2;color:#b91c1c}.pm td.off{font-weight:700;background:repeating-linear-gradient(135deg,#fff 0 3px,#bbb 3px 4px)}.pm td.na{background:#e2e8f0}.meta .key{display:inline-block;padding:0 4px;margin:0 1px;border-radius:2px;font-weight:700}
@media print{body{background:#fff}.toolbar{display:none}.sheet{width:auto;max-width:none;min-height:0;margin:0;padding:0;box-shadow:none;break-before:page}.sheet.lead{break-before:auto}}`;

export const PRINT_SCRIPT = `const b=document.body,ds=[...document.querySelectorAll('.day,.ttday')];function update(){const d=b.dataset.day;b.classList.toggle('all',d==='all');ds.forEach(x=>x.classList.toggle('hide',d!=='all'&&x.dataset.d!==d));document.querySelectorAll('.lead').forEach(x=>x.classList.remove('lead'));const first=[...document.querySelectorAll('.sheet')].find(x=>x.getClientRects().length);if(first)first.classList.add('lead');document.querySelectorAll('[data-pick]').forEach(x=>x.classList.toggle('on',x.dataset.pick===d));const tt=b.dataset.mode==='tt';document.querySelectorAll('button[data-mode]').forEach(x=>x.classList.toggle('on',x.dataset.mode===b.dataset.mode));const on=document.querySelector('[data-pick].on');document.title=(tt?'個人TT_':'シフト_')+(on?on.dataset.label:'');}document.querySelectorAll('button[data-mode]').forEach(x=>x.onclick=()=>{b.dataset.mode=x.dataset.mode;update();scrollTo(0,0);});document.querySelectorAll('[data-pick]').forEach(x=>x.onclick=()=>{b.dataset.day=x.dataset.pick;update();scrollTo(0,0);});document.getElementById('fullName').onchange=e=>b.classList.toggle('full',e.target.checked);document.getElementById('withPeople').onchange=e=>b.classList.toggle('no-people',!e.target.checked);update();`;
